server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Container name as label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      # Container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      
      # Container labels
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      
      # Only collect logs from UGM-AICare containers
      - source_labels: ['__meta_docker_container_name']
        regex: '/(ugm_aicare_.*)'
        action: keep
    
    # Parse JSON logs from Python backend
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            agent: agent
            session_id: session_id
            processing_time_ms: processing_time_ms
            crisis_level: crisis_level
            intervention_plan_id: intervention_plan_id
      
      # Add labels from parsed JSON
      - labels:
          level:
          agent:
          crisis_level:
      
      # Format timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano
