"""Aggregated admin schema exports."""
from .appointments import (
    AppointmentResponse,
    AppointmentUpdate,
    AppointmentUser,
    PsychologistResponse,
    TherapistScheduleCreate,
    TherapistScheduleResponse,
    TherapistScheduleUpdate,
)
from .content_resources import (
    ContentResourceCreate,
    ContentResourceItem,
    ContentResourceResponse,
)
from .conversations import (
    ConversationDetailResponse,
    ConversationListItem,
    ConversationStats,
    ConversationsResponse,
    SessionDetailResponse,
    SessionListItem,
    SessionListResponse,
    SessionUser,
)
from .dashboard import AppointmentSummary, FeedbackSummary
from .interventions import (
    CampaignMetrics,
    CampaignSummary,
    ExecutionSummary,
    InterventionCampaignCreate,
    InterventionCampaignListResponse,
    InterventionCampaignResponse,
    InterventionCampaignUpdate,
    InterventionExecutionListResponse,
    InterventionExecutionResponse,
    InterventionExecutionUpdate,
    InterventionOverview,
    InterventionSettings,
    InterventionSettingsUpdate,
    ManualInterventionCreate,
    QueueItem,
)
from .system import (
    SystemSettingItem,
    SystemSettingsCategory,
    SystemSettingsResponse,
)
from .flags import (
    FlagCreate,
    FlagResponse,
    FlagUpdate,
    FlagsBulkCloseRequest,
    FlagsBulkTagRequest,
    FlagsSummary,
)
from .users import UserDetailResponse, UserListItem, UserStats, UsersResponse
from .triage import (
    SeverityBreakdown,
    ProcessingMetrics,
    TriageCasePreview,
    TriageOverview,
    TriageAssessmentItem,
    TriageAssessmentListResponse,
    TriageTestRequest,
    TriageTestResponse,
)

__all__ = [
    "AppointmentResponse",
    "AppointmentUpdate",
    "AppointmentUser",
    "PsychologistResponse",
    "TherapistScheduleCreate",
    "TherapistScheduleResponse",
    "TherapistScheduleUpdate",
    "ContentResourceCreate",
    "ContentResourceItem",
    "ContentResourceResponse",
    "ConversationDetailResponse",
    "ConversationListItem",
    "ConversationStats",
    "ConversationsResponse",
    "SessionDetailResponse",
    "SessionListItem",
    "SessionListResponse",
    "SessionUser",
    "AppointmentSummary",
    "FeedbackSummary",
    "CampaignMetrics",
    "CampaignSummary",
    "ExecutionSummary",
    "InterventionCampaignCreate",
    "InterventionCampaignListResponse",
    "InterventionCampaignResponse",
    "InterventionCampaignUpdate",
    "InterventionExecutionListResponse",
    "InterventionExecutionResponse",
    "InterventionExecutionUpdate",
    "InterventionOverview",
    "InterventionSettings",
    "InterventionSettingsUpdate",
    "ManualInterventionCreate",
    "QueueItem",
    "SystemSettingItem",
    "SystemSettingsCategory",
    "SystemSettingsResponse",
    "FlagCreate",
    "FlagResponse",
    "FlagUpdate",
    "FlagsBulkCloseRequest",
    "FlagsBulkTagRequest",
    "FlagsSummary",
    "UserDetailResponse",
    "UserListItem",
    "UserStats",
    "UsersResponse",
    "SeverityBreakdown",
    "ProcessingMetrics",
    "TriageCasePreview",
    "TriageOverview",
    "TriageAssessmentItem",
    "TriageAssessmentListResponse",
    "TriageTestRequest",
    "TriageTestResponse",
]
