"""A Mako template for creating Alembic migration scripts.

This template is used by the ``alembic revision`` command to generate
a new migration script.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756c4fde7a1b'
down_revision = 'c613d13854de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.drop_constraint('agent_messages_run_id_fkey', 'agent_messages', type_='foreignkey')
    op.create_foreign_key(None, 'agent_messages', 'agent_runs', ['run_id'], ['id'])
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.add_column('surveys', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'category')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.create_foreign_key('agent_messages_run_id_fkey', 'agent_messages', 'agent_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    # ### end Alembic commands ###
