"""added new models

Revision ID: 887dff92e7a0
Revises: 
Create Date: 2025-05-15 23:24:34.093898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887dff92e7a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_summaries_id', table_name='user_summaries')
    op.drop_index('ix_user_summaries_user_id', table_name='user_summaries')
    op.drop_table('user_summaries')
    op.drop_index('ix_user_badges_badge_id', table_name='user_badges')
    op.drop_index('ix_user_badges_contract_address', table_name='user_badges')
    op.drop_index('ix_user_badges_id', table_name='user_badges')
    op.drop_index('ix_user_badges_user_id', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index('ix_email_logs_id', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_google_sub', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_twitter_id', table_name='users')
    op.drop_index('ix_users_wallet_address', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_email_templates_id', table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index('ix_tweets_id', table_name='tweets')
    op.drop_index('ix_tweets_tweet_id', table_name='tweets')
    op.drop_table('tweets')
    op.drop_index('ix_journal_entries_entry_date', table_name='journal_entries')
    op.drop_index('ix_journal_entries_id', table_name='journal_entries')
    op.drop_index('ix_journal_entries_user_id', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_feedback_id', table_name='feedback')
    op.drop_index('ix_feedback_session_id', table_name='feedback')
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_email_recipients_id', table_name='email_recipients')
    op.drop_table('email_recipients')
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_index('ix_conversations_session_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_email_groups_id', table_name='email_groups')
    op.drop_table('email_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('email_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='email_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_email_groups_id', 'email_groups', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    op.create_index('ix_conversations_session_id', 'conversations', ['session_id'], unique=False)
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.create_table('email_recipients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['email_groups.id'], name='email_recipients_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_recipients_pkey')
    )
    op.create_index('ix_email_recipients_id', 'email_recipients', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ease_of_use_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chatbot_understanding_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('felt_understood_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nps_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_achieved', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('improvement_suggestion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedback_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    op.create_index('ix_feedback_session_id', 'feedback', ['session_id'], unique=False)
    op.create_index('ix_feedback_id', 'feedback', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='journal_entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='journal_entries_pkey'),
    sa.UniqueConstraint('user_id', 'entry_date', name='_user_entry_date_uc')
    )
    op.create_index('ix_journal_entries_user_id', 'journal_entries', ['user_id'], unique=False)
    op.create_index('ix_journal_entries_id', 'journal_entries', ['id'], unique=False)
    op.create_index('ix_journal_entries_entry_date', 'journal_entries', ['entry_date'], unique=False)
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sentiment_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    op.create_index('ix_tweets_tweet_id', 'tweets', ['tweet_id'], unique=False)
    op.create_index('ix_tweets_id', 'tweets', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('email_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='email_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_email_templates_id', 'email_templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('twitter_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_activity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('allow_email_checkins', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_wallet_address', 'users', ['wallet_address'], unique=False)
    op.create_index('ix_users_twitter_id', 'users', ['twitter_id'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_google_sub', 'users', ['google_sub'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipients', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sent_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name='email_logs_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_logs_pkey')
    )
    op.create_index('ix_email_logs_id', 'email_logs', ['id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_badges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_badges_pkey'),
    sa.UniqueConstraint('transaction_hash', name='user_badges_transaction_hash_key'),
    sa.UniqueConstraint('user_id', 'badge_id', name='_user_badge_uc')
    )
    op.create_index('ix_user_badges_user_id', 'user_badges', ['user_id'], unique=False)
    op.create_index('ix_user_badges_id', 'user_badges', ['id'], unique=False)
    op.create_index('ix_user_badges_contract_address', 'user_badges', ['contract_address'], unique=False)
    op.create_index('ix_user_badges_badge_id', 'user_badges', ['badge_id'], unique=False)
    op.create_table('user_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_summaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_summaries_pkey')
    )
    op.create_index('ix_user_summaries_user_id', 'user_summaries', ['user_id'], unique=False)
    op.create_index('ix_user_summaries_id', 'user_summaries', ['id'], unique=False)
    # ### end Alembic commands ###
