"""Graph specification for the Orchestrator agent visualization."""

ORCHESTRATOR_GRAPH_SPEC = {
    "id": "orchestrator",
    "name": "Query Orchestrator",
    "nodes": [
        {
            "id": "receive_question",
            "label": "Receive Question",
            "description": "Accept natural language question from user interface.",
            "column": 0,
            "row": 0,
        },
        {
            "id": "classify_intent",
            "label": "Classify Intent",
            "description": "Determine which Safety agent should respond based on intent, consent, and role.",
            "column": 1,
            "row": 0,
        },
        {
            "id": "route_sta",
            "label": "Route to STA",
            "description": "Answer questions about triage risk signals or live safety posture.",
            "column": 2,
            "row": -1,
        },
        {
            "id": "route_sca",
            "label": "Route to SCA",
            "description": "Provide coaching plan context or outreach cadence details.",
            "column": 2,
            "row": 0,
        },
        {
            "id": "route_sda",
            "label": "Route to SDA",
            "description": "Surface case assignments, SLA timers, and escalation status.",
            "column": 2,
            "row": 1,
        },
        {
            "id": "route_ia",
            "label": "Route to IA",
            "description": "Answer insights and privacy-preserving analytics questions.",
            "column": 2,
            "row": 2,
        },
        {
            "id": "collect_response",
            "label": "Collect Response",
            "description": "Gather results from the selected agent and format for user.",
            "column": 3,
            "row": 0,
        },
        {
            "id": "return_answer",
            "label": "Return Answer",
            "description": "Send final formatted answer back to user interface.",
            "column": 4,
            "row": 0,
        },
    ],
    "edges": [
        {"source": "receive_question", "target": "classify_intent"},
        {
            "source": "classify_intent",
            "target": "route_sta",
            "condition": "intent == 'sta'",
            "label": "Safety triage",
        },
        {
            "source": "classify_intent",
            "target": "route_sca",
            "condition": "intent == 'sca'",
            "label": "Coaching plans",
        },
        {
            "source": "classify_intent",
            "target": "route_sda",
            "condition": "intent == 'sda'",
            "label": "Case management",
        },
        {
            "source": "classify_intent",
            "target": "route_ia",
            "condition": "intent == 'ia'",
            "label": "Insights requests",
        },
        {"source": "route_sta", "target": "collect_response"},
        {"source": "route_sca", "target": "collect_response"},
        {"source": "route_sda", "target": "collect_response"},
        {"source": "route_ia", "target": "collect_response"},
        {"source": "collect_response", "target": "return_answer"},
    ],
}