"""change_to_implement_cbt

Revision ID: 45159d79a7e5
Revises: c8f5659f72fb
Create Date: 2025-05-20 01:07:23.110501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45159d79a7e5'
down_revision: Union[str, None] = 'c8f5659f72fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_id', sa.String(), nullable=True))

    op.execute("UPDATE conversations SET conversation_id = gen_random_uuid()::text WHERE conversation_id IS NULL")

    op.alter_column('conversations', 'conversation_id',
                    existing_type=sa.String(),
                    nullable=False)
    
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_column('conversations', 'conversation_id')
    # ### end Alembic commands ###
