"""idk what this update was I forgor but its important

Revision ID: 86d476e8c71e
Revises: 45159d79a7e5
Create Date: 2025-05-23 15:35:30.323179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d476e8c71e'
down_revision: Union[str, None] = '45159d79a7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_prompts_category'), 'journal_prompts', ['category'], unique=False)
    op.create_index(op.f('ix_journal_prompts_id'), 'journal_prompts', ['id'], unique=False)
    op.add_column('journal_entries', sa.Column('prompt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal_entries', 'journal_prompts', ['prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'prompt_id')
    op.drop_index(op.f('ix_journal_prompts_id'), table_name='journal_prompts')
    op.drop_index(op.f('ix_journal_prompts_category'), table_name='journal_prompts')
    op.drop_table('journal_prompts')
    # ### end Alembic commands ###
