"""added new models

Revision ID: c8f5659f72fb
Revises: 
Create Date: 2025-05-15 23:26:17.976554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f5659f72fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_summaries', sa.Column('summarized_session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_summaries_summarized_session_id'), 'user_summaries', ['summarized_session_id'], unique=False)
    op.drop_constraint('user_summaries_user_id_fkey', 'user_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'user_summaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_summaries', type_='foreignkey')
    op.create_foreign_key('user_summaries_user_id_fkey', 'user_summaries', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_summaries_summarized_session_id'), table_name='user_summaries')
    op.drop_column('user_summaries', 'summarized_session_id')
    # ### end Alembic commands ###
